--SELECT rowid, *
--FROM Rating
--INSERT INTO Movie(mID,title,year,director)
--VALUES(109,'Harry Potter',2001,'Mark')
--INSERT INTO Movie(mID,title,year,director)
--VALUES(110,'Loh',)
--UPDATE Rating SET stars = 5 WHERE mID < 105
--UPDATE Reviewer SET name 'i know right'
--DELETE FROM Rating
--DELETE FROM Rating WHERE stars >=4
