site_name: Документация по лабораторной работе №3
nav:
 - Home: index.md
 - "Описание":
     - "Описание программной системы": opisanie.md
     - "Описание СУБД": subd.md
     - "Описание таблиц СУБД": table_subd.md
     - "Код создания БД": code.md
     - "Код добавления данных": insert.md