Title: ITMO OPBD
site_name: OPBD Ishmanov
site_url: https://kibarik.github.io/ITMO_FSPO_DataBases_2020-2021/
Summary: Лабораторные работы по ОПБД
Authors: Ishmanov Aleksey
Date:    June 20, 2021
nav:
  - Главная: index.md
  - Описание БД: lab3.md
  - MongoDB: mongodb.md
theme: readthedocs
